# Site settings
title: Anik Hasan
description: 'Dev things'
url: '1ik.github.io'
baseurl: '/'
google_analytics: 'UA-79205439-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Anik Hasan'
  #email: 'ping@anik.rocks'
  twitter_username: heyanik
  #facebook_username: joshgerdes
  github_username:  1ik
  #linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
